######################################################################
# Automatically generated by qmake (3.0) ?? ?? 19 15:25:47 2018
######################################################################

QT +=widgets
TEMPLATE = app
TARGET = QMakeTest
INCLUDEPATH += .

# Input
SOURCES += Test.cpp
